"""add sort_order to indicators

Revision ID: 53bf893ce4ce
Revises: facb191af1e5
Create Date: 2026-09-06 14:53:51.737740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bf893ce4ce'
down_revision: Union[str, None] = 'facb191af1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'indicators',
        sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'sort_order')
    # ### end Alembic commands ###
