"""add region to indicators

Revision ID: f0840ec64b0b
Revises: 53bf893ce4ce
Create Date: 2026-09-06 16:31:16.854991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0840ec64b0b'
down_revision: Union[str, None] = '53bf893ce4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'indicators',
        sa.Column('region', sa.String(length=16), nullable=False, server_default='GLOBAL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'region')
    # ### end Alembic commands ###
